//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIntranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSection
    {
        public AppSection()
        {
            this.Configs = new HashSet<Config>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Config> Configs { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
