//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIntranet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyIntranetEntities : DbContext
    {
        public MyIntranetEntities()
            : base("name=MyIntranetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserComms> UserComms { get; set; }
        public virtual DbSet<UserHr> UserHrs { get; set; }
        public virtual DbSet<LeaveRequest> LeaveRequests { get; set; }
        public virtual DbSet<OfficeClosure> OfficeClosures { get; set; }
        public virtual DbSet<UserSocial> UserSocials { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<AppSection> AppSections { get; set; }
        public virtual DbSet<UserHrDependencies> UserHrDependencies { get; set; }
        public virtual DbSet<Absence> Absences { get; set; }
        public virtual DbSet<AbsenceReasons> AbsenceReasons { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
    }
}
