//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIntranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int Id { get; set; }
        public string RoleName { get; set; }
        public int AppSectionId { get; set; }
    
        public virtual UserRoles UserRole { get; set; }
        public virtual AppSection AppSection { get; set; }
    }
}
