//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIntranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserRoles = new HashSet<UserRoles>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int DepartmentId { get; set; }
        public string Gender { get; set; }
        public string Title { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string UserName { get; set; }
        public bool Active { get; set; }
        public System.DateTime DateStarted { get; set; }
        public Nullable<System.DateTime> DateLeft { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual UserHr UserHr { get; set; }
        public virtual UserSocial UserSocial { get; set; }
        public virtual UserComms UserComm { get; set; }
        public virtual ICollection<UserRoles> UserRoles { get; set; }
    }
}
