//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIntranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHr
    {
        public UserHr()
        {
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.UserHrDependencies = new HashSet<UserHrDependencies>();
            this.Absences = new HashSet<Absence>();
        }
    
        public int Id { get; set; }
        public decimal ContractedHours { get; set; }
        public decimal Salary { get; set; }
        public string ShiftPattern { get; set; }
        public short LeaveThisYear { get; set; }
        public short LeaveNextYear { get; set; }
        public int LeaveSupervisor { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        public virtual ICollection<UserHrDependencies> UserHrDependencies { get; set; }
        public virtual ICollection<Absence> Absences { get; set; }
    }
}
